<?php
// Generated by ZF2's ./bin/classmap_generator.php

return array(
    'TsvUsers\Module'                        => __DIR__ . '/Module.php',
    'TsvUsers\Controller\TsvUsersController' => __DIR__ . '/src/TsvUsers/Controller/TsvUsersController.php',
    'TsvUsersTest\Framework\TestCase'        => __DIR__ . '/tests/TsvUsers/Framework/TestCase.php',
    'TsvUsersTest\SampleTest'                => __DIR__ . '/tests/TsvUsers/SampleTest.php',
);
